openapi: 3.1.0
info:
  title: World API
  description: REST API for accessing World DB
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/cities:
    get:
      tags:
        - city
      operationId: getAllCities
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/City"

  /api/cities/{id}:
    get:
      tags:
        - city
      operationId: getCityById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/City"

  /api/cities/country/{code}:
    get:
      tags:
        - city
      operationId: getCitiesByCountryCode
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/City"

components:
  schemas:
    City:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        countryCode:
          type: string
        district:
          type: string
        population:
          type: integer
          format: int32
        localName:
          type: string
